[package]
org = "mosip"
name = "kafkaHub"
version = "1.2.0-patch.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
modules = ["inittopic"]
groupId = "io.mosip"
artifactId = "kafka-admin-client"
version = "1.2.0.1"
path = "kafka-admin-client/target/kafka-admin-client-1.2.0.1.jar"
